name: Build and Publish OpenELIS Demo DB
on:
  push:
    branches:
      - master

    paths:
      - '.github/workflows/build_publish_openelis_demoDB.yml'
      - 'package/docker/demoDB/**'
      - 'scripts/database/**'

  repository_dispatch:
    types: ['bahmni-scripts-trigger']

env:
  BAHMNI_VERSION: 0.94

jobs:
  docker-build-publish:
    name: Build & Publish OpenELIS Demo DB Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Docker Build and push
        uses: docker/build-push-action@v2
        with:
          file: package/docker/demoDB/Dockerfile
          push: true
          tags: bahmni/openelis-db:demo-${{env.BAHMNI_VERSION}}-${{github.run_number}},bahmni/openelis-db:demo-latest
