name: Build and Publish OpenELIS Demo DB
on:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
      - "package/docker/Dockerfile"
      - "package/docker/scripts/docker_build_openelis.sh"
      - "package/docker/scripts/docker_publish_openelis.sh"
      - "package/docker/scripts/docker_build_openelis_freshDB.sh"
      - 'package/docker/scripts/docker_build.sh'
      - "package/docker/scripts/docker_publish_openelis_freshDB.sh"
      - "package/docker/scripts/configureDB.sh"
      - "package/docker/scripts/start.sh"
      - "package/docker/scripts/run-implementation-openelis-implementation.sh"
  repository_dispatch:
    types: ["bahmni-scripts-trigger"]

env:
  BAHMNI_VERSION: 0.94

jobs:
  docker-build-publish:
    name: Build & Publish OpenELIS Demo DB Docker Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetching Database Backup Data in build scripts
        uses: actions/checkout@v2
        with:
          repository: Bahmni/bahmni-scripts
          path: bahmni-scripts
      - name: Build Docker Image
        run: ./package/docker/scripts/docker_build_openelis_demoDB.sh
      - name: Push Docker Images
        run: ./package/docker/scripts/docker_publish_openelis_demoDB.sh
        env:
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN}}
